blank_issues_enabled: false
contact_links:
  - name: Matrix Channel (Support)
    url: https://matrix.to/#/#tenacity:libera.chat
    about: "Please ask questions etc here. You need to be logged into IRC to join. For IRC, #tenacity at irc.libera.chat."
  - name: Discussions
    url: https://github.com/tenacityteam/tenacity/discussions/categories/q-a
    about: Please ask questions here. You should use the IRC/Matrix channel instead (#tenacity on irc.libera.chat)
