name: Packaging
on:
  push:
    branches:
      - master
  pull_request:
    paths:
      - /packaging/flatpak/**
  workflow_dispatch:

jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-40
      options: --privileged
    strategy:
      matrix:
        arch: [x86_64, aarch64]
      fail-fast: false
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    # Emulate to provide ARM support
    - name: Install deps
      run: |
        dnf -y install docker ninja-build
    - name: Set up QEMU
      id: qemu
      uses: docker/setup-qemu-action@v1
      with:
        image: tonistiigi/binfmt:latest
        platforms: arm64
    - uses: bilelmoussaoui/flatpak-github-actions/flatpak-builder@v4
      with:
        bundle: tenacity.flatpak
        manifest-path: packaging/flatpak/org.tenacityaudio.Tenacity.json
        cache-key: flatpak-builder-${{ github.sha }}
        arch: ${{ matrix.arch }}
